version: 2.1
jobs:
  build:
    working_directory: ~/neoscan-2
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: type check
          command: npm run ts-buld
      - run:
          name: lint
          command: npm run ci-lint
      - run:
          name: test
          command: npm run test

workflows:
  version: 2
  build:
    jobs:
      - build
